name: Seats Functional Test Travelstart B2C

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

env:
  MAVEN_OPTS: "-Xmx4g"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'  # Combines cache step

      - name: Build with Maven
        run: mvn clean install -B

      - name: Run Tests
        run: |
          mvn test \
          -Dsurefire.suiteXmlFiles=src/test/java/testRunners/seatsTest.xml \
          -Dmaven.test.failure.ignore=false \
          -B

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports/