name: Java CI with Maven

on:
  schedule:
    # Runs every day at 3:30 AM UTC (9:00 AM IST)
    - cron: "30 3 * * *"
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # Run the specific test using Maven
      - name: Run bookingFlow.xml Test
        run: mvn -B test -Dsurefire.suiteXmlFiles=src/test/java/testRunners/bookingFlow.xml

      # Optional: Update dependency graph
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
